# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2ec9f205bbde38e5166a9c185f7cb95de6767daa7dd9568c7368c434d9be85988b6a498ff9e295538ac465dd49b171eb33f7e1b1aa147b6f706b762292f40be

test:
  secret_key_base: e0d69d13a17539abd2e1184507d256c8feff622e2317bbf954e29a2859a55bbce1e56c1da90d709bc2949ab3c76bf4daddf2146d85681c84ffb71a3760a8644d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
